# Generated by Django 3.1.1 on 2024-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
